// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TollFee.Api.Models;

namespace TollFee.Api.Migrations
{
    [DbContext(typeof(TollDBContext))]
    [Migration("20230829113122_DatesConfiguration")]
    partial class DatesConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TollFee.Api.Models.Fee", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<long>("FromMinute")
                        .HasColumnType("bigint");

                    b.Property<long>("ToMinute")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(2,0)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Year", "FromMinute", "ToMinute", "Price");

                    b.ToTable("Fee");
                });

            modelBuilder.Entity("TollFee.Api.Models.TollFree", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Year", "Date");

                    b.ToTable("TollFree");
                });
#pragma warning restore 612, 618
        }
    }
}
